### ISSUE TITLE
'Named' added to exports

### ISSUE THREAD

**Issue by shumphrey** [mairatma/babel-plugin-globals#3]
The string 'Named' is added to the export name.

The documentation does not say this will happen.
I am unclear on the reason why 'Named' is being added.

**Comment by mairatma** [comment]
This is just to distinguish named exports from default exports on the globals.

For example, let's say you have a file named `Foo.js`. If it exports via `export default whatever;` then the exported variable will be available at `this.yourGlobal.Foo`. But, if it exports using `export {whatever, Bar}`, these will be available at `this.yourGlobalNamed.Foo.whatever` and `this.yourGlobalNamed.Bar` instead. This way you can have both types of exports without conflicts.

I agree that this **Named** suffix is not very nice, but that was the simplest thing I came up with at the time I built this plugin to make sure it worked. Also, I was using it mostly for default exports anyway. I'm definitely open to better suggestions though, and you're right that I didn't explain it on the docs, so I can do that at least.

**Comment by shumphrey** [comment]
This makes sense.
I can't immediately think of anything better.
If the default export were only ever a function it would be easier as you could do 

```
GlobalName.ModuleName = function default() {}
GlobalName.ModuleName.function2 = //whatever
```

But the default could be something else so that won't work.

**Comment by mairatma** [comment]
I'm closing this since the documentation was added already (thanks @shumphrey).
